baseURL = "http://melaniewickert.de/"
languageCode = "en-us"
title = "MelanieWickert.de"
theme = "mel"

[params]
		footer = "&copy; 2018 Melanie Wickert | All rights reserved | Built with [Hugo](https://gohugo.io/) and hosted on [Netlify](https://www.netlify.com/)"

[blackfriday]
  hrefTargetBlank = true
