baseURL = "http://melaniewickert.de/"
languageCode = "en-us"
title = "MelanieWickert.de"
theme = "mel"

[params]
    description = "The online presence of Melanie Wickert"
		footer = "&copy; 2018 Melanie Wickert | All rights reserved"
